# Generated by Django 4.2.11 on 2024-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0002_hocki_hoatdong_quy_che_quyche_diem_toi_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
