# Generated by Django 4.2.11 on 2024-04-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0003_like_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
