# Generated by Django 4.2.11 on 2024-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersv',
            name='hoat_dongs',
            field=models.ManyToManyField(null=True, to='DRL.hoatdong'),
        ),
    ]
