# Generated by Django 4.2.11 on 2024-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0006_alter_usersv_hoat_dongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersv',
            name='hoat_dongs',
            field=models.ManyToManyField(blank=True, to='DRL.hoatdong'),
        ),
    ]
