# Generated by Django 4.2.11 on 2024-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0007_alter_usersv_hoat_dongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersv',
            name='hoat_dongs',
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='user_svs',
            field=models.ManyToManyField(blank=True, to='DRL.usersv'),
        ),
    ]
