# Generated by Django 4.2.11 on 2024-04-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0008_remove_usersv_hoat_dongs_hoatdong_user_svs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersv',
            name='thanh_tich_ngoai_khoa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DRL.thanhtichngoaikhoa'),
        ),
    ]
