# Generated by Django 4.2.11 on 2024-04-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0009_usersv_thanh_tich_ngoai_khoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersv',
            name='thanh_tich_ngoai_khoa',
        ),
        migrations.AddField(
            model_name='thanhtichngoaikhoa',
            name='sinh_vien',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DRL.usersv'),
        ),
    ]
