# Generated by Django 4.2.11 on 2024-05-07 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0011_alter_hoatdong_options_alter_hocki_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersv',
            name='ngay_nhap_hoc',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 19, 43, 32, 127023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='usersv',
            name='ngay_sinh',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 19, 43, 32, 127023, tzinfo=datetime.timezone.utc)),
        ),
    ]
