# Generated by Django 4.2.11 on 2024-05-08 05:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0012_usersv_ngay_nhap_hoc_usersv_ngay_sinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdong',
            name='hoc_ki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DRL.hocki'),
        ),
        migrations.AddField(
            model_name='thanhtichngoaikhoa',
            name='hoc_ki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DRL.hocki'),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_nhap_hoc',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 5, 26, 47, 938611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_sinh',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 5, 26, 47, 938611, tzinfo=datetime.timezone.utc)),
        ),
    ]
