# Generated by Django 4.2.11 on 2024-05-08 06:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0013_hoatdong_hoc_ki_thanhtichngoaikhoa_hoc_ki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvienminhchunghoatdong',
            name='nguoi_kiem_tra_minh_chung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_minh_chung_hoat_dong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_nhap_hoc',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 6, 52, 57, 413697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_sinh',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 6, 52, 57, 413697, tzinfo=datetime.timezone.utc)),
        ),
    ]
