# Generated by Django 4.2.11 on 2024-05-08 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0014_sinhvienminhchunghoatdong_nguoi_kiem_tra_minh_chung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvienminhchunghoatdong',
            name='minh_chung',
            field=models.FileField(upload_to='D:\\Django_DRL\\SystemDRL\\DRLProj/DRL/static/minh_chung/'),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_nhap_hoc',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_sinh',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
