# Generated by Django 4.2.11 on 2024-05-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0015_alter_sinhvienminhchunghoatdong_minh_chung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersv',
            name='ngay_nhap_hoc',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usersv',
            name='ngay_sinh',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
