# Generated by Django 4.2.11 on 2024-05-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0016_alter_usersv_ngay_nhap_hoc_alter_usersv_ngay_sinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhtichngoaikhoa',
            name='sinh_vien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DRL.usersv'),
        ),
    ]
