# Generated by Django 4.2.11 on 2024-05-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0017_alter_thanhtichngoaikhoa_sinh_vien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoatdong',
            name='user_svs',
        ),
    ]
