# Generated by Django 4.2.11 on 2024-05-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0018_remove_hoatdong_user_svs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdong',
            name='user_svs',
            field=models.ManyToManyField(blank=True, to='DRL.usersv'),
        ),
    ]
