# Generated by Django 4.2.11 on 2024-05-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRL', '0021_hoatdong_sv_hoatdong_user_svs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoatdong',
            name='user_svs',
        ),
        migrations.DeleteModel(
            name='HoatDong_SV',
        ),
    ]
